/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.fpa.service;import jakarta.validation.constraints.NotBlank;import org.springframework.stereotype.Service;import java.util.*;
/**
 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
 */
@Service public class ForecastSubmissionGovernanceService{/**
                                                           * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                           */
public Assessment assess(Request r){List<String>b=new ArrayList<>(),a=new ArrayList<>();if(!r.costCentersReconciled())b.add("成本中心数据未完成对账");if(!r.assumptionsVersioned())b.add("预测假设未版本化");if(!r.ownerAssigned())b.add("预测未指定业务责任人");if(!r.intercompanyEliminated())b.add("内部交易未抵销");if(!r.finalApprovalComplete())b.add("最终审批未完成");if(r.deadlinePassed())b.add("提交截止时间已过且无批准例外");if(!b.isEmpty()){a.add("阻止提交并补齐对账、假设、责任和审批控制");return new Assessment(Decision.BLOCKED,b,a);}if(!r.materialVarianceExplained()||!r.scenarioComparisonComplete()){if(!r.materialVarianceExplained())a.add("解释重大预算与预测偏差");if(!r.scenarioComparisonComplete())a.add("补充基准、乐观和压力情景对比");return new Assessment(Decision.REVIEW,b,a);}a.add("提交滚动预测并冻结假设、情景和审批版本");return new Assessment(Decision.SUBMIT,b,a);}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   */
public record Request(@NotBlank String forecastCycle,boolean costCentersReconciled,boolean assumptionsVersioned,boolean ownerAssigned,boolean intercompanyEliminated,boolean finalApprovalComplete,boolean deadlinePassed,boolean materialVarianceExplained,boolean scenarioComparisonComplete){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    */
public record Assessment(Decision decision,List<String>blockers,List<String>actions){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          */
public enum Decision{SUBMIT,REVIEW,BLOCKED}}
