/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.fpa.service;import org.junit.jupiter.api.Test;import static org.assertj.core.api.Assertions.assertThat;/**
                                                                                                                            * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                            */
class ForecastSubmissionGovernanceServiceTest{private final ForecastSubmissionGovernanceService service=new ForecastSubmissionGovernanceService();/**
                                                                                                                                                                                                                                                                              * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                              */
@Test void submitsGovernedForecast(){var r=service.assess(new ForecastSubmissionGovernanceService.Request("2026-M09",true,true,true,true,true,false,true,true));assertThat(r.decision()).isEqualTo(ForecastSubmissionGovernanceService.Decision.SUBMIT);}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       */
@Test void blocksFinancialControlGaps(){var r=service.assess(new ForecastSubmissionGovernanceService.Request("2026-M10",false,false,false,false,false,true,true,true));assertThat(r.blockers()).hasSize(6);}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   */
@Test void reviewsVarianceAndScenarioGaps(){var r=service.assess(new ForecastSubmissionGovernanceService.Request("2026-M11",true,true,true,true,true,false,false,false));assertThat(r.actions()).hasSize(2);}}
