/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.fpa.controller;import cn.zhuatech.fpa.common.ApiResponse;import cn.zhuatech.fpa.service.ForecastSubmissionGovernanceService;import jakarta.validation.Valid;import org.springframework.web.bind.annotation.*;/**
                                                                                                                                                                                                                                  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                  */
@RestController @RequestMapping("/api/enterprise/fpa")public class ForecastSubmissionGovernanceController{private final ForecastSubmissionGovernanceService service;/**
                                                                                                                                                                                                                                                                                                                                                                                                      * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                      */
public ForecastSubmissionGovernanceController(ForecastSubmissionGovernanceService service){this.service=service;}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       */
@PostMapping("/forecast-submission")public ApiResponse<ForecastSubmissionGovernanceService.Assessment>assess(@Valid @RequestBody ForecastSubmissionGovernanceService.Request request){return ApiResponse.ok(service.assess(request));}}
